# A collection of test for Project 9 in the Full Stack JavaScript Techdegree

### Create Course (Minimum Data)
POST http://localhost:5000/api/courses HTTP/1.1
Authorization: Basic joe@smith.com:joepassword
Content-Type: application/json

{
  "title": "My new course",
  "description": "This is the course I created",
  "userId": 1
}

### Get Courses
GET http://localhost:5000/api/courses HTTP/1.1
